spring:
  application:
    name: liquidonline-server

  profiles:
    active: local

  mvc:
    view:
      prefix: none
      suffix: none

server:
  error:
    whitelabel:
      enabled: false
    include-message: always